name: List of Services README Generation

on:
  schedule:
    - cron: 30 */2 * * *
  workflow_dispatch:

jobs:
  readme-services:
   name: Generate Services List
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        ref: 'main'

    - name: Install yq
      uses: dcarbone/install-yq-action@4075b4dca348d74bd83f2bf82d30f25d7c54539b # v1.3.1

    - name: Generate service list
      run: |
        yq 'explode(.) | .services | to_entries | map({"service": .key, "image": (.value.image | sub("@sha256:.*$"; "")), "description": (.value.labels."homepage.description" // "")})' docker-compose.yml > services.yml

    - name: Generate Markdown Table
      uses: gazab/create-markdown-table@6686233d7008e8d8b9d4bbdbfd1fb1ae510019f0 # v1.0.7
      id: service-table
      with:
        file: ./services.yml

    - name: Regenerate README
      run: |
        echo "# List of Services" > README.md
        echo -e "\n\n" >> README.md
        echo "${{ steps.service-table.outputs.table }}" >> README.md

    - name: Add/Commit README.md
      id: commit-readme
      uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
      with:
        message: "chore: Update README"
        add: "README.md"